# Generated by Django 5.0.6 on 2024-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseMoney',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
