# Generated by Django 5.0.6 on 2024-06-06 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_alter_basemoney_amount_alter_incomesource_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesource',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
