# Generated by Django 5.0.6 on 2024-06-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_expensesource_date_incomesource_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='frequency',
            field=models.CharField(choices=[('OT', 'One-Time'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='OT', max_length=2),
        ),
    ]
