# Generated by Django 5.0.6 on 2024-06-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0004_incomesource_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='frequency',
            field=models.CharField(choices=[('OT', 'One-Time'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly'), ('R', 'Repeated')], default='OT', max_length=2),
        ),
    ]
