# Generated by Django 5.0.6 on 2024-06-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0005_alter_incomesource_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesource',
            name='frequency',
        ),
    ]
