# Generated by Django 5.0.6 on 2024-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0007_expensesource_time_incomesource_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseMoney',
            name='typeofacc',
            field=models.CharField(choices=[('BA', 'Bank Account'), ('CC', 'Credit Card'), ('CASH', 'Cash')], default='CASH', max_length=5),
        ),
    ]
