# Generated by Django 5.0.6 on 2024-06-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0009_alter_basemoney_typeofacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemoney',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
