# Generated by Django 5.0.6 on 2024-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0011_alter_basemoney_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemoney',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
