# Generated by Django 5.0.6 on 2024-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0012_alter_basemoney_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemoney',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
