# Generated by Django 5.0.6 on 2024-06-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0013_alter_basemoney_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemoney',
            name='spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
