# Generated by Django 5.0.6 on 2024-06-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0015_alter_basemoney_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemoney',
            name='spent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
